version: '3'
services:
  app:
    build:
      args:
        BUILD_ENV: dev
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000

  proxy:
    volumes:
      - ./src/public:/usr/share/nginx/html